### ISSUE TITLE
Management

### ISSUE THREAD

**Issue by lucretor** [lucretor/united-we-fly#11]
- [x] Χρώματα gradient (αριστερή πλευρά): #6e6e71, #cae5e9 
- [x] Χρώμα κειμένων (δεξιά πλευρά): #6e6e71
- [x] padding

**Comment by Kolokuthokeftes** [comment]
MANAGEMENT:

United We Fly empowers new artists and presents them with opportunities and support in the context of a worldwide network of professional partners. Besides the production and distribution of music records, the agency supports musicians along the way by providing them with strategic management. From helping artists identify their goals, to creating the detailed strategy that will confidently and successfully guide them through their next steps, United We Fly works passionately towards the visibility and promotion of artists and their work by booking and promoting concerts, music showcases, networking events and festivals at great venues throughout Greece and Europe.

**Comment by lucretor** [comment]
- [ ] padding
