### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by Kolokuthokeftes** [lucretor/united-we-fly#13]
Έχω προσθέσει ό,τι υλικό έχουμε για τα Previous Events, αλλά πρέπει να υπάρχει ένα μπέρδεμα με το πώς καταχωρείται η ημερομηνία. Δηλαδή: ενώ θεωωρητικά όλα τα events που έχω βάλει είναι previous, δύο από αυτά τα καταχωρεί ως next. Οι  κανονικές ημερομηνίες αυτών είναι 10.04.17 & 11.05.17 - DD.ΜΜ.YY, αλλά διαβάζονται ως MM.DD.YY, και εμφανίζονται στα Next. 
Κάποια άλλα δεν εμφανίζονται πουθενά στη λίστα, ενώ τα έχω περάσει.

**Comment by lucretor** [comment]
Διόρθωσα το format σε DD.ΜΜ.YY. To ότι πάνε λάθος στα next, είναι θέμα σύγκρισης που κάναμε με διαφορετικό format, θα διορθωθεί αύριο συν τα υπόλοιπα για να τα δούμε
