### ISSUE TITLE
Vision

### ISSUE THREAD

**Issue by Kolokuthokeftes** [lucretor/united-we-fly#14]
Κείμενο για Vision Page:

OUR VISION

United We Fly is an independent music agency, founded in 2015 and based in Athens, Greece. Offering high quality 360 music services, we aim at cultivating a strong sense of belonging to musicians. Our vision revolves around an ambition to place contemporary Greek artists on the competitive music industry world map. Our dedicated team supports and represents Greek musicians who share United We Fly’ s values by providing them with a wide range of services related to music production and business. From record releases, production and manufacturing, to distribution and sales management, our goal is to create an all-inclusive ‘music house’. We believe in innovation: we promote a musician-centered approach, setting the foundations for a productive future that will enable the Greek music industry to thrive and compete in global markets.

- [x] Done
- [x] degrees
- [x] %padding keimeno pio panw

**Comment by lucretor** [comment]
- [ ] degrees

- [ ] %padding keimeno pio panw
