### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Kolokuthokeftes** [lucretor/united-we-fly#15]
Contact Us
General Enquiries: info@unitedwefly.com
Press Enquiries: press@unitedwefly.com
Music Sampling: demo@unitedwefly.com  

Subscribe
Full Name
Email
Country
Submit 

Address
2 Adrianiou Str.
Athens 11525 Greece
t. 0030 210 6985340

- [x] Contacts padding
- [x] Subscribe mailchimp

**Comment by lucretor** [comment]
- [ ] Contacts padding

- [ ] Subscribe mailchimp
