### ISSUE TITLE
Publishing & Synchronization (deadline Παρασκευή 29.09)

### ISSUE THREAD

**Issue by Kolokuthokeftes** [lucretor/united-we-fly#16]
- [x] Δημιουργία της νέας σελίδας, με λίστα καλλιτεχνών
- [x] Περιεχόμενο σελίδας κάθε καλλιτέχη: Κείμενο, φωτογραφία
- [x] Στέλνω άμεσα φωτογραφίες με mockups

**Comment by lucretor** [comment]
Done

**Comment by Kolokuthokeftes** [comment]
- [ ] Μόλις έμαθα ότι δεν μπορούμε να ονομάσουμε έτσι τη σελίδα (θέματα νομικά) και γιαυτό θα την ονομάσουμε 'United We Fly Composers'
- [ ] Να μην εμφανίζονται σε αυτή τη σελίδα οι Artists: Theodore & Afformance
- [ ] Πρόσθεσα όλους τους Artists με τις πληροφορίες και φωτογραφίες, αλλά θέλω να εμφανίζονται με την αντίστροφη σειρά, δλδ: πρώτος: Theodore Polyschronopoulos, τελευταίος: Vasilis Dokakis

**Comment by Kolokuthokeftes** [comment]
Ευχαριστώωωω! Είστε οι καλυτερότεροι! 
Λουκούμια Συριανά τρώτε? Να σας φέρω?
- [ ] ΝΑΙ
- [ ] ΟΧΙ
